### ISSUE TITLE
Consider adding Gradle foojay plugin for toolchain management

### ISSUE THREAD

**Issue by StefMa** [svenjacobs/reveal#175]
I wanted to run the samples(demo) and got greeted with the issue `can't find required toolchain jdk 21 MACOS.. yada yada`.
The problem is that I obviously haven't installed a JDK 21 on my machine.

To make developers life a bit more easier we can fix this by adding the [foojay plugin](https://github.com/gradle/foojay-toolchains) to the top-level `settings.gradle.kts` file:
```kotlin
plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version "0.8.0"
}
```

This will automatically download and use the requested toolchain (in case there is no local version available).

**Comment by svenjacobs** [comment]
Thanks for the information. I didn't know about this plugin.
Do you want to create a pull request? 😃
