### ISSUE TITLE
Balloon shape not correct and Arrow missing on Android API 29 and API 30

### ISSUE THREAD

**Issue by StefMa** [svenjacobs/reveal#176]
**Describe the bug**
We are using Balloon together with an Arrow and releazied that the shape is not how it should be.
I also run the demo within this project and it faces the same problem.
Here is a screenshot:
![Screenshot 2024-10-24 at 10 33 48 AM](https://github.com/user-attachments/assets/2f4ebbca-a2c2-476b-b640-be4a8b84ba61)

Left is API 29, right is API 30, middle is API 33 and how it should (and I expect) look like.

* The Balloon has no rounded corners
* The arrow is missing

**To Reproduce**
Run the demo app on an API 29 and API 30 Emulator.

**Expected behavior**
Expected is that it looks identical on all Android versions.
According to the source code you have minSDK defined as API 21.
So I would expect it works until that version. Even though **we** only need support for 26+ 😁 

**Screenshots**
See above ☝️ 

**Sample project**
The demo within this repo.

**Smartphone (please complete the following information):**
 - Device: I guess this doesnt matter, we are using various Pixel emulators for testing.
 - Android version: We found this only in API 29 and API 30. 
The followig Android APIs are good (according to internal testing):
26, 27, 28, 33, 34, 35 

Didn't tested: 31 and 32

**Version**
3.1.0, but we also saw this in 3.0.8

**Additional context**
n/a

**Comment by StefMa** [comment]
I just had a quick chat with GitHub Copilot and it came up with a solution that actually works 😅 
I have no idea if this is a good solution though 🤷 
```diff
diff --git a/reveal-shapes/src/commonMain/kotlin/com/svenjacobs/reveal/shapes/balloon/Balloon.kt b/reveal-shapes/src/commonMain/kotlin/com/svenjacobs/reveal/shapes/balloon/Balloon.kt
index 5d0bf2c..21d0a6c 100644
--- a/reveal-shapes/src/commonMain/kotlin/com/svenjacobs/reveal/shapes/balloon/Balloon.kt
+++ b/reveal-shapes/src/commonMain/kotlin/com/svenjacobs/reveal/shapes/balloon/Balloon.kt
@@ -7,9 +7,12 @@ import androidx.compose.foundation.layout.padding
 import androidx.compose.runtime.Composable
 import androidx.compose.ui.Alignment
 import androidx.compose.ui.Modifier
+import androidx.compose.ui.draw.clip
+import androidx.compose.ui.draw.shadow
 import androidx.compose.ui.graphics.Brush
 import androidx.compose.ui.graphics.Color
 import androidx.compose.ui.graphics.graphicsLayer
+import androidx.compose.ui.platform.LocalDensity
 import androidx.compose.ui.unit.Dp
 import androidx.compose.ui.unit.dp
 
@@ -86,15 +89,8 @@ private fun Balloon(
 ) {
 	Box(
 		modifier = modifier
-			.graphicsLayer {
-				shadowElevation = elevation.toPx()
-				shape = BalloonShape(
-					arrow = arrow,
-					cornerRadius = cornerRadius,
-					density = this@graphicsLayer,
-				)
-				clip = true
-			}
+			.shadow(elevation, BalloonShape(arrow, cornerRadius, LocalDensity.current))
+			.clip(BalloonShape(arrow, cornerRadius, LocalDensity.current))
 			.then(backgroundModifier)
 			.padding(arrow.padding),
 		contentAlignment = contentAlignment,
```

Some discussion snippets with Copilot that might be relevant.
> The issue you're experiencing with the Balloon shape on Android API 29 and API 30 could be related to the way the GenericShape and graphicsLayer APIs handle clipping and drawing on these specific API levels. There are known differences in how certain graphics operations are handled across different Android versions. [...] 

> To ensure the Balloon shape is rendered correctly on Android API 29 and API 30, you can try the following additional changes:  [...]
> Use LayerModifier for Clipping: Instead of relying solely on graphicsLayer, you can use LayerModifier to ensure proper clipping and drawing.

Then I asked how to use the `LayerModifier` and it came up with the solution posted above ☝️ 
And it works:
![Screenshot 2024-10-24 at 1 03 48 PM (1)](https://github.com/user-attachments/assets/7953b9eb-07c1-4722-8e69-ec11c1affa91)

**Comment by svenjacobs** [comment]
Interesting, thanks for the bug report and the solution ❤️ So AI bots can be useful after all 😂 
I don't remember why I used `graphicsLayer()` but I'm glad you found a solution.

Does it also work if you combine `shadow()` and `clip()` into one?

```kotlin
.shadow(
  elevation = elevation,
  shape = BalloonShape(arrow, cornerRadius, LocalDensity.current),
  clip = true,
)
```
