### ISSUE TITLE
llegalArgumentException: Revealable with key "key_name" not found

### ISSUE THREAD

**Issue by jayesh408** [svenjacobs/reveal#39]
**We're getting this prod issue:**
Fatal Exception: java.lang.IllegalArgumentException: Revealable with key "key_name" not found
       at com.svenjacobs.reveal.RevealState.reveal(RevealState.kt:69)

I'm wondering what could've caused this, as 2 revealables before this one were shown and clicking on next we're showing this but it crashed with above exception. 

Is there any known issue @svenjacobs ?

**Comment by svenjacobs** [comment]
Hello @jayesh408, I'm not aware of any known issue. Can you please provide a sample project where this is reproducible?

**Comment by svenjacobs** [comment]
Did this solve the problem? Can I close this issue? 😃

**Comment by jayesh408** [comment]
Not sure yet, as wasn't able to reproduce. Have made the changes will monitor prod. 
Lets close this, and big thank you 🙇‍♂️
