### ISSUE TITLE
Status bar padding issue

### ISSUE THREAD

**Issue by aazizbekyan** [svenjacobs/reveal#49]
There's an issue focusing a menu item from toolbar: the status bar padding is not taken into account.

The issue seems to be stemming from the `RevealScope#revealable()` where [`layoutCoordinates.positionInRoot()`](https://github.com/svenjacobs/reveal/blob/371cd5803f722ec415679a9289d5b1043c655df8/reveal-core/src/main/kotlin/com/svenjacobs/reveal/RevealScope.kt#L127) gets coordinates from a root composable which has a status bar padding, but then this coordinates are used inside [`Fullscreen` composable](https://github.com/svenjacobs/reveal/blob/371cd5803f722ec415679a9289d5b1043c655df8/reveal-core/src/main/kotlin/com/svenjacobs/reveal/internal/fullscreen/Fullscreen.kt#L20) which does not have status bar padding information and lays out the `Balloon` with incorrect top padding:

<img width="359" alt="Screenshot 2023-07-04 at 14 56 46" src="https://github.com/svenjacobs/reveal/assets/78498008/f9c33f7d-4467-4d3d-942e-0082fe466b89">

Currently there is no way of overriding this behavior via passing a `Modifier` instance from client side. The `RevealScope.revealable()` accepts `PaddingValues` but that one is for the internal padding and cannot be used to pad the `Balloon` from the top of the screen.

**Comment by svenjacobs** [comment]
Hello Andranik, thank for your bug report. Could you please provide a sample project which demonstrates this issue? Thank you!

**Comment by aazizbekyan** [comment]
While trying to assemble the demo project I identified that the issues was that the theme of the activity had following flag declared:

```
<item name="android:fitsSystemWindows">true</item>
```

Removing this flag fixes the issue.
I think this github issue can be closed. Thanks!
