### ISSUE TITLE
Scrollin in lazygrid or lazycolum

### ISSUE THREAD

**Issue by blackbirdsr71br** [svenjacobs/reveal#50]
Great library, it is very good, I just wanted to know how I can reveal a component that is in a lazycolumn or a lazygrid since they do not have the focus and the scroll so that it can be seen.

**Comment by svenjacobs** [comment]
Hello,

you could add a [onGloballyPositioned](https://developer.android.com/reference/kotlin/androidx/compose/ui/layout/OnGloballyPositionedModifier) modifier to the element which you want to reveal. Once it reaches a certain position (becomes visible on the screen), you could start the reveal effect.

**Comment by svenjacobs** [comment]
Please also see my comment [here](https://github.com/svenjacobs/reveal/issues/48#issuecomment-1637643598).
