### ISSUE TITLE
Compose Multiplatform

### ISSUE THREAD

**Issue by DATL4G** [svenjacobs/reveal#59]
Please change this android-only project to Kotlin Multiplatform with the according https://github.com/JetBrains/compose-multiplatform implementation.

This way it would be possible to use it for Android, Desktop, Browser and iOS

**Comment by svenjacobs** [comment]
I started a [discussion](https://github.com/svenjacobs/reveal/discussions/40) about this. Unfortunately a migration is not that simple.

**Comment by svenjacobs** [comment]
@DATL4G I'm happy to announce that version [3.0](https://github.com/svenjacobs/reveal/releases/tag/v3.0.0) supports Compose Multiplatform!
